[package]
name = "rust-embed"
version = "6.3.0"
description = "Rust Custom Derive Macro which loads files into the rust binary at compile time during release and loads the file from the fs during dev"
readme = "readme.md"
documentation = "https://docs.rs/rust-embed"
repository = "https://github.com/pyros2097/rust-embed"
license = "MIT"
keywords = ["http", "rocket", "static", "web", "server"]
categories = ["web-programming", "filesystem"]
authors = ["pyros2097 <pyros2097@gmail.com>"]
edition = "2018"

[[example]]
name = "warp"
path = "examples/warp.rs"
required-features = ["warp-ex"]

[[example]]
name = "actix"
path = "examples/actix.rs"
required-features = ["actix"]

[[example]]
name = "rocket"
path = "examples/rocket.rs"
required-features = ["rocket"]

[[example]]
name = "axum"
path = "examples/axum.rs"
required-features = ["axum-ex"]

[[example]]
name = "poem"
path = "examples/poem.rs"
required-features = ["poem-ex"]

[[example]]
name = "nickel"
path = "examples/nickel.rs"
required-features = ["nickel-ex"]

[[test]]
name = "interpolated_path"
path = "tests/interpolated_path.rs"
required-features = ["interpolate-folder-path"]

[[test]]
name = "include_exclude"
path = "tests/include_exclude.rs"
required-features = ["include-exclude"]

[dependencies]
walkdir = "2.3.1"
rust-embed-impl = { version = "6.2.0", path = "impl"}
rust-embed-utils = { version = "7.1.0", path = "utils"}

include-flate = { version = "0.1", optional = true, features = ["stable"] }
actix-web = { version = "3", default-features = false, optional = true }
mime_guess = { version = "2", optional = true }
hex = { version = "0.4.3", optional = true }
tokio = { version = "1.0", optional = true, features = ["macros", "rt-multi-thread"] }
warp = { version = "0.3", default-features = false, optional = true }
rocket = { version = "0.5.0-rc.1", default-features = false, optional = true }
axum = { version = "0.4", default-features = false, features = ["http1"], optional = true  }
poem = { version = "1.0.8", default-features = false, optional = true  }
salvo = { version = "0.16", default-features = false, optional = true  }
nickel = { version = "0.11.0", optional = true }

[dev-dependencies]
sha2 = "0.9"

[features]
debug-embed = ["rust-embed-impl/debug-embed", "rust-embed-utils/debug-embed"]
interpolate-folder-path = ["rust-embed-impl/interpolate-folder-path"]
compression = ["rust-embed-impl/compression", "include-flate"]
include-exclude = ["rust-embed-impl/include-exclude", "rust-embed-utils/include-exclude"]
actix = ["actix-web", "mime_guess"]
warp-ex = ["warp", "tokio", "mime_guess"]
axum-ex = ["axum", "tokio", "mime_guess"]
poem-ex = ["poem", "tokio", "mime_guess", "hex"]
salvo-ex = ["salvo", "tokio", "mime_guess", "hex"]
nickel-ex = ["nickel", "mime_guess"]


[badges]
appveyor = { repository = "pyros2097/rust-embed" }
travis-ci = { repository = "pyros2097/rust-embed" }
is-it-maintained-issue-resolution = { repository = "pyros2097/rust-embed" }
is-it-maintained-open-issues = { repository = "pyros2097/rust-embed" }
maintenance = { status = "passively-maintained" }

[workspace]
members = ["impl", "utils"]

